// This file was generated by a tool. Do not edit!
// AST classes for stmt
namespace Eleu.Ast;

public abstract class Stmt {
  public interface Visitor<R> {
    R VisitBlockStmt(Block stmt);
    R VisitClassStmt(Class stmt);
    R VisitExpressionStmt(Expression stmt);
    R VisitFunctionStmt(Function stmt);
    R VisitIfStmt(If stmt);
    R VisitPrintStmt(Print stmt);
    R VisitReturnStmt(Return stmt);
    R VisitVarStmt(Var stmt);
    R VisitWhileStmt(While stmt);
  }

  public abstract R Accept<R>(Visitor<R> visitor);

  // Nested Stmt classes here...
//> stmt-block
  public class Block : Stmt {
    public readonly List<Stmt> Statements;

    internal Block(List<Stmt> Statements) {
      this.Statements = Statements;
    }

    public override R Accept<R>(Visitor<R> visitor) {
      return visitor.VisitBlockStmt(this);
    }
  }
//< stmt-block
//> stmt-class
  public class Class : Stmt {
    public readonly string Name;
    public readonly Expr.Variable? Superclass;
    public readonly List<Stmt.Function> Methods;

    internal Class(string Name,
          Expr.Variable? Superclass,
          List<Stmt.Function> Methods) {
      this.Name = Name;
      this.Superclass = Superclass;
      this.Methods = Methods;
    }

    public override R Accept<R>(Visitor<R> visitor) {
      return visitor.VisitClassStmt(this);
    }
  }
//< stmt-class
//> stmt-expression
  public class Expression : Stmt {
    public readonly Expr expression;

    internal Expression(Expr expression) {
      this.expression = expression;
    }

    public override R Accept<R>(Visitor<R> visitor) {
      return visitor.VisitExpressionStmt(this);
    }
  }
//< stmt-expression
//> stmt-function
  public class Function : Stmt {
    public readonly FunctionType Type;
    public readonly string Name;
    public readonly List<Token> Paras;
    public readonly List<Stmt> Body;

    internal Function(FunctionType Type,
          string Name,
          List<Token> Paras,
          List<Stmt> Body) {
      this.Type = Type;
      this.Name = Name;
      this.Paras = Paras;
      this.Body = Body;
    }

    public override R Accept<R>(Visitor<R> visitor) {
      return visitor.VisitFunctionStmt(this);
    }
  }
//< stmt-function
//> stmt-if
  public class If : Stmt {
    public readonly Expr Condition;
    public readonly Stmt ThenBranch;
    public readonly Stmt? ElseBranch;

    internal If(Expr Condition, Stmt ThenBranch, Stmt? ElseBranch) {
      this.Condition = Condition;
      this.ThenBranch = ThenBranch;
      this.ElseBranch = ElseBranch;
    }

    public override R Accept<R>(Visitor<R> visitor) {
      return visitor.VisitIfStmt(this);
    }
  }
//< stmt-if
//> stmt-print
  public class Print : Stmt {
    public readonly Expr expression;

    internal Print(Expr expression) {
      this.expression = expression;
    }

    public override R Accept<R>(Visitor<R> visitor) {
      return visitor.VisitPrintStmt(this);
    }
  }
//< stmt-print
//> stmt-return
  public class Return : Stmt {
    public readonly Token Keyword;
    public readonly Expr? Value;

    internal Return(Token Keyword, Expr? Value) {
      this.Keyword = Keyword;
      this.Value = Value;
    }

    public override R Accept<R>(Visitor<R> visitor) {
      return visitor.VisitReturnStmt(this);
    }
  }
//< stmt-return
//> stmt-var
  public class Var : Stmt {
    public readonly string Name;
    public readonly Expr? Initializer;

    internal Var(string Name, Expr? Initializer) {
      this.Name = Name;
      this.Initializer = Initializer;
    }

    public override R Accept<R>(Visitor<R> visitor) {
      return visitor.VisitVarStmt(this);
    }
  }
//< stmt-var
//> stmt-while
  public class While : Stmt {
    public readonly Expr Condition;
    public readonly Stmt Body;

    internal While(Expr Condition, Stmt Body) {
      this.Condition = Condition;
      this.Body = Body;
    }

    public override R Accept<R>(Visitor<R> visitor) {
      return visitor.VisitWhileStmt(this);
    }
  }
//< stmt-while
}
